# Generated by Django 6.1.1 on 2026-09-20 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_formfield_taskdefinition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار اجرا'), ('RUNNING', 'در حال اجرا'), ('SUCCESS', 'موفق'), ('FAILED', 'ناموفق'), ('TIMED_OUT', 'پایان مهلت زمانی')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای ورودی کاربر')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای خروجی AI')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا و آمار اجرا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='catalog.task', verbose_name='تسک')),
                ('task_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='catalog.taskdefinition', verbose_name='نسخه تعریف تسک')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_runs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اجرای تسک',
                'verbose_name_plural': 'اجراهای تسک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
