# Generated by Django 6.1.1 on 2026-09-16 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('label', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('field_type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('select', 'Select'), ('multi_select', 'Multi select'), ('number', 'Number'), ('boolean', 'Boolean')], max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('validation', models.JSONField(default=dict)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='catalog.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('role', models.TextField()),
                ('process', models.JSONField(default=list)),
                ('rules', models.JSONField(default=list)),
                ('constraints', models.JSONField(default=list)),
                ('output_structure', models.CharField(choices=[('free_text', 'Free text'), ('markdown', 'Markdown'), ('json', 'JSON'), ('template', 'Template')], max_length=20)),
                ('output_template', models.TextField(blank=True, null=True)),
                ('examples', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='catalog.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'version'), name='unique_task_definition_version')],
            },
        ),
    ]
